# Generated by Django 2.2.2 on 2019-08-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0002_regismentor_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='regismentor',
            name='grad_year',
            field=models.CharField(default=None, max_length=4, verbose_name='Graduation year'),
        ),
    ]
