# Generated by Django 2.2.2 on 2019-08-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0003_regismentor_grad_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='regismentor',
            name='Batch_id',
            field=models.CharField(default=None, max_length=8, verbose_name='Batch Id'),
        ),
    ]
